# Render ke dynamic port ko bind karne ke liye yeh sabse zaroori hai
server.port=${PORT:8080}

# Database URL mein agar SSL issue hai toh use thoda flexible banate hain
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:fitness_db}?useSSL=true&trustServerCertificate=true&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:Root@123}
spring.jpa.hibernate.ddl-auto=update